name: "Update materialization"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
jobs:
  update:
    name: "Update materialization"
    runs-on: macos-latest
    steps:
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD HH:mm:ss
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= s3.kdevlab.com:PhuKrzVfCsS0T1R4FnslJy2qUBul9oQ2CTSO/fg/llM= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://hydra.iohk.io https://nix-cache.s3.kdevlab.com https://cache.nixos.org/
      - name: Install niv, jq, nix-prefetch-git, node2nix
        run: |
          nix-env -iA niv gnugrep bash -f https://github.com/miuirussia/nixpkgs/tarball/nixpkgs-unstable
      - name: Update dependencies
        run: |
          niv -s sources/sources.json update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update materialization
        run: |
          rm -rf ./materialized-*
          ./update.sh
          git status
          git add materialized-*
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
           commit_message: Automatic materialization update – ${{ steps.current-time.outputs.formattedTime }}
           status_options: '--untracked-files=all'
