name: "Update materialization"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
jobs:
  build-materialization:
    strategy:
      matrix:
        ghc: ['865', '884', '8106', '8107']
    name: "Build materialization on ghc${{ matrix.ghc }}"
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          install_url: https://github.com/miuirussia/nix-unstable-installer/releases/latest/download/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= s3.kdevlab.com:PhuKrzVfCsS0T1R4FnslJy2qUBul9oQ2CTSO/fg/llM= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://hydra.iohk.io https://nix-cache.s3.kdevlab.com https://cache.nixos.org/
      - uses: cachix/cachix-action@v10
        with:
          name: kdevlab
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build materialization
        run: |
          nix build --print-build-logs --no-link .#materialization.x86_64-darwin.ghc${{ matrix.ghc }}

  update:
    name: "Update materialization"
    needs: build-materialization
    runs-on: macos-latest
    steps:
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD HH:mm:ss
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          install_url: https://github.com/miuirussia/nix-unstable-installer/releases/latest/download/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= s3.kdevlab.com:PhuKrzVfCsS0T1R4FnslJy2qUBul9oQ2CTSO/fg/llM= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://hydra.iohk.io https://nix-cache.s3.kdevlab.com https://cache.nixos.org/
      - uses: cachix/cachix-action@v10
        with:
          name: kdevlab
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Check flakes
        run: |
          nix flake show
      - name: Update dependencies
        run: |
          nix flake update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update materialization
        run: |
          nix --print-build-logs run .#generateMaterialization -- $(pwd)/materialized-macOS
          git status
          git add materialized-*
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
           commit_message: Automatic materialization update – ${{ steps.current-time.outputs.formattedTime }}
           status_options: '--untracked-files=all'
