name: "Update materialization"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
jobs:
  update-dependencies:
    name: "Update dependencies"
    runs-on: macos-latest
    outputs:
      release_id: ${{ steps.push.outputs.release_id }}
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%s)"
      - uses: actions/checkout@v2
      - name: Install nix
        uses: miuirussia/install-nix-action@master
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          install_url: https://github.com/miuirussia/nix-unstable-installer/releases/latest/download/install
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
            substituters = https://hydra.iohk.io https://nix-cache.s3.kdevlab.com https://cache.nixos.org/
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= s3.kdevlab.com:PhuKrzVfCsS0T1R4FnslJy2qUBul9oQ2CTSO/fg/llM= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - name: Check flakes
        run: |
          nix flake show
      - name: Update flakes
        run: |
          nix flake update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        id: push
        env:
          RELEASE_ID: v0.1.${{ steps.date.outputs.date }}
        run: |
          echo $RELEASE_ID > version
          git add flake.lock version
          git commit -m "Release $RELEASE_ID"
          git push origin HEAD:update/"$RELEASE_ID"
          git tag "$RELEASE_ID"
          git push origin "$RELEASE_ID"
          echo "::set-output name=release_id::$RELEASE_ID"

  build-materialization:
    strategy:
      matrix:
        ghc: ['865', '884', '8106', '8107']
    name: "Build materialization on ghc${{ matrix.ghc }}"
    needs: [update-dependencies]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: update/${{ needs.update-dependencies.outputs.release_id }}
      - name: Install nix
        uses: miuirussia/install-nix-action@master
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          install_url: https://github.com/miuirussia/nix-unstable-installer/releases/latest/download/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= s3.kdevlab.com:PhuKrzVfCsS0T1R4FnslJy2qUBul9oQ2CTSO/fg/llM= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://hydra.iohk.io https://nix-cache.s3.kdevlab.com https://cache.nixos.org/
      - uses: cachix/cachix-action@v10
        with:
          name: kdevlab
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build materialization
        run: |
          nix build --print-build-logs --no-link .#materialization.x86_64-darwin.ghc${{ matrix.ghc }}

  update-materialization:
    name: "Update materialization"
    needs: [update-dependencies, build-materialization]
    runs-on: macos-latest
    steps:
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD HH:mm:ss
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: update/${{ needs.update-dependencies.outputs.release_id }}
      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - name: Install nix
        uses: miuirussia/install-nix-action@master
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          install_url: https://github.com/miuirussia/nix-unstable-installer/releases/latest/download/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= s3.kdevlab.com:PhuKrzVfCsS0T1R4FnslJy2qUBul9oQ2CTSO/fg/llM= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://hydra.iohk.io https://nix-cache.s3.kdevlab.com https://cache.nixos.org/
      - uses: cachix/cachix-action@v10
        with:
          name: kdevlab
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Update materialization
        run: |
          nix --print-build-logs run .#generateMaterialization -- $(pwd)/materialized-macOS
          git status
          git add materialized-*
      - name: Push materialization
        env:
          RELEASE_ID: ${{ needs.update-dependencies.outputs.release_id }}
        run: |
          echo $RELEASE_ID > materialization
          git add materialization
          git commit -m "Update materialization $RELEASE_ID"
          git push origin HEAD:update/"$RELEASE_ID"

  release:
    name: Release
    needs: [update-dependencies, update-materialization]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - name: Update master branch
        env:
          RELEASE_ID: ${{ needs.update-dependencies.outputs.release_id }}
        run: |
          git merge origin/update/"$RELEASE_ID"
          git push origin "$GITHUB_REF"
          git tag -f "$RELEASE_ID"
          git push -f origin "$RELEASE_ID"
          git push origin -d update/"$RELEASE_ID"
